### ISSUE TITLE
Almost only fail reports at CPAN Testers

### ISSUE THREAD

**Issue by eserte** [gempesaw/saucerest-perl#1]
See http://matrix.cpantesters.org/?dist=WWW-Saucelabs%200.01 for a fail/pass overview.

**Comment by gempesaw** [comment]
Ah, thanks for the reminder. I hadn't planned to release it to CPAN, and then someone asked me personally for it, so I threw it up there haphazardly. Tests had passed locally but failed due to a breaking change in a dependency that I didn't have the updated version of locally, so I have it on my to-do list to clean them up. Thanks!
